server:
  port: 8082

spring:

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
  application:
    name: auth-service

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: false
    status-page-url-path: /actuator/health
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URI:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    enable:
      resilience4j.circuitbreaker: true

jwt:
  secret: ${JWT_SECRET:M0c1suuRkDAJx2qLWuAfQre3tXyzopQ8 }
  expiration: 86400000

rabbitmq:
  user:
    exchange: user.exchange
    queue: user.queue
    created:
      routing-key: user.created

feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

resilience4j:
  circuitbreaker:
    instances:
      user-service:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
  retry:
    instances:
      user-service:
        maxAttempts: 3
        waitDuration: 1000
